tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "inverse-on-surface": "#dff4ff",
                "surface-container-lowest": "#ffffff",
                "surface-variant": "#cfe6f2",
                "surface-container-highest": "#cfe6f2",
                "secondary-fixed-dim": "#bac9d3",
                "on-primary-container": "#9fefb6",
                "background": "#f3faff",
                "on-primary": "#ffffff",
                "primary-fixed": "#a4f4bb",
                "on-tertiary-container": "#dddede",
                "on-secondary-fixed": "#0f1d25",
                "on-background": "#071e27",
                "tertiary-fixed": "#e2e2e2",
                "surface-container": "#dbf1fe",
                "secondary": "#526069",
                "on-secondary-fixed-variant": "#3b4951",
                "tertiary-container": "#606262",
                "tertiary-fixed-dim": "#c6c6c7",
                "surface-bright": "#f3faff",
                "surface-container-high": "#d5ecf8",
                "inverse-surface": "#1e333c",
                "on-secondary-container": "#56656e",
                "surface": "#f3faff",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#3f4941",
                "on-secondary": "#ffffff",
                "surface-tint": "#196c3f",
                "on-surface": "#071e27",
                "outline-variant": "#bfc9be",
                "outline": "#6f7a70",
                "on-tertiary-fixed-variant": "#454747",
                "on-tertiary-fixed": "#1a1c1c",
                "on-error": "#ffffff",
                "secondary-fixed": "#d6e5ef",
                "primary-fixed-dim": "#88d8a1",
                "surface-container-low": "#e6f6ff",
                "on-primary-fixed": "#00210e",
                "surface-dim": "#c7dde9",
                "secondary-container": "#d3e2ed",
                "on-primary-fixed-variant": "#00522c",
                "inverse-primary": "#88d8a1",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "primary-container": "#1d6f42",
                "tertiary": "#484a4b",
                "primary": "#00552e",
                "error": "#ba1a1a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "sidebar-width": "280px",
                "gutter": "1rem",
                "container-padding-mobile": "1rem",
                "stack-md": "1rem",
                "stack-lg": "2rem",
                "bottom-nav-height": "64px",
                "stack-sm": "0.5rem",
                "container-padding-desktop": "2.5rem"
            },
            "fontFamily": {
                "label-md": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "headline-xl": ["Inter", "sans-serif"],
                "headline-lg": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "code-snippet": ["monospace"],
                "body-sm": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "label-sm": ["Inter", "sans-serif"]
            },
        },
    },
};
